name: auto
on: 
  schedule:
    - cron: '0 0 * * 0,4'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: build-bqn
          build-args: |
            NATIVE=0
            BRANCH=develop
      - 
        name: Get Zip
        run: docker run -v ".:/opt/mount" --rm -d build-bqn
      -
        name: Get sha256
        run: |
          SHA256=$(sha256sum bqn.zip | awk '{print $1}')
          echo "SHA256=${SHA256}" >> $GITHUB_ENV
      -
        name: Delete previous release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/auto"; then
            gh release delete auto -y
          fi
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto
          draft: false
          prerelease: true
          files: bqn.zip
          body: |
            Automatically generated release.

            Branch: develop.

            | file    | SHA256              |
            | ------- | ------------------- |
            | bqn.zip | `${{ env.SHA256 }}` |

            Included:
              - BQN.exe: stand alone executable
              - libcbqn/cbqn.dll: CBQN as a dynamic library
              - libcbqn/cbqn.lib: for linking cbqn.dll
              - libcbqn/bqnffi.h: C header file
              - licenses/: licenses for CBQN
              
            Note:
              * uses UCRT 
              * UTF-8 support for BQN.exe should work for Windows 10 Version 1903 or later, and Windows 11
