name: auto
on: 
  schedule:
    - cron: '0 0 * * 0,4'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: build-bqn
          build-args: |
            NATIVE=0
            BRANCH=develop
      - 
        name: Get Zip
        run: docker run -v ".:/opt/mount" --rm -d build-bqn
      -
        name: Get sha256
        run: sha256sum bqn.zip > sha256.txt
      -
        name: Delete previous release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/auto"; then
            gh release delete auto --cleanup-tag -y
          fi
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto
          draft: false
          prerelease: true
          body: |
            Automatically generated release.

            Includes: licenses, libcbqn, and standalone executable. Branch: develop.
          files: |
            bqn.zip
            sha256.txt
